apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway-deployment
  labels:
    app: flyway
spec:
  selector:
    matchLabels:
      app: flyway
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flyway
    spec:
      containers:
        - name: flywaydemo
          image: kesavakimmich/flyway-demo:null-dbc4f0c
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: flyway-service
  labels:
    app: flyway
spec:
  selector:
    app: flyway
  ports:
    - protocol: TCP
      port: 8081
